doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Core/Domain/Migrations'
    # namespace is arbitrary but should be different from App\Core\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
